### ISSUE TITLE
Adding Animation to the blog cards

### ISSUE THREAD

**Issue by aksy2512** [RobotronicsClubIITMandi/URC_Mars_Rover#22]
Hi!
I suggest adding animations to the blog cards. I've included a video below about the potential change.

https://user-images.githubusercontent.com/79045568/210461718-bf67dc42-e983-4f8a-b6aa-f41a4985a532.mp4

I also suggest changing the background color of the navigation. The details of this can be seen in the video above.

Kindly approve the animation or suggest any change which can be done so that I can create a pull request.
Thanks

**Comment by AnuragMaurya-PreD** [comment]
Please go ahead. We need to update the visuals of the website. Any other suggestions are welcome.
