### ISSUE TITLE
Typewriter effect in the blog page

### ISSUE THREAD

**Issue by aksy2512** [RobotronicsClubIITMandi/URC_Mars_Rover#27]
I suggest implementing a typewriter effect for the blog page's content to improve the visuals. Below is a video of the implementation,

https://user-images.githubusercontent.com/79045568/214353233-043d52ee-0c81-4441-b20f-5d2522ce37c1.mp4

The implementation makes use of javascript along with some logic to display

**Comment by AnuragMaurya-PreD** [comment]
Sure, go ahead

**Comment by AnuragMaurya-PreD** [comment]
Closing the issue
