### ISSUE TITLE
Map section in Sponsor Us Page

### ISSUE THREAD

**Issue by aksy2512** [RobotronicsClubIITMandi/URC_Mars_Rover#31]
I suggest updating the map section on the Sponsor Us Page since it looks very simple and doesn't convey all the necessary contact details.

 I propose the following design for it  -
1) Web view
![image](https://user-images.githubusercontent.com/79045568/216829602-4ce0a51c-73a3-4f77-97d6-fa04504f54b8.png)

2) Mobile view
![image](https://user-images.githubusercontent.com/79045568/216829707-944194f6-ec3a-4d7f-9b16-cf9414f865f8.png)

Thanks

**Comment by AnuragMaurya-PreD** [comment]
Please go ahead.
Let me know if you need some more info

**Comment by AnuragMaurya-PreD** [comment]
Issue resolved
